# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: Default

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'

- task: Docker@2
  displayName: 'Docker Login'
  inputs:
    containerRegistry: 'dockerHubCon'
    command: 'login'

- task: Docker@2
  displayName: 'Docker build Image'
  inputs:
    containerRegistry: 'dockerHubCon'
    repository: 'deepika210/aksdemoapi'
    command: 'build'
    Dockerfile: '**/dockerfile'

- task: Docker@2
  displayName: 'Docker push image on DockerHub'
  inputs:
    containerRegistry: 'dockerHubCon'
    repository: 'deepika210/aksdemoapi'
    command: 'push'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact : Drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
